### ISSUE TITLE
Anonymous / everyone needs change permissions on language.

### ISSUE THREAD

**Issue by euhm** [valdisiljuconoks/localization-provider-epi#3]
Hello,

in the query handler EPiServerAvailableLanguages you check if the current identity has edit access for a specific language. (QueryEditAccessRights()).

In a default setup this works, as 'everyone' has by default change (edit) rights. But we tweak these permissions, to avoid that content editor of country x can change translations of country y.

Is there a reason that you enforce edit rights to enable a language?

For the moment I configured a custom handler without the check (where clause).

kind regards,

bob

**Comment by valdisiljuconoks** [comment]
hi,

i think this initially was added to verify that specific user has edit access to that language to provide edit options inside admin ui. this might conflict a bit, i agree.

let me think through this..

**Comment by valdisiljuconoks** [comment]
Hi,

So in your setup editor A will have access to language X, but not to language Y? How you differentiate countries? do you distinguish those only by language (culture) in epi?

Idea of the edit access filter was to prevent (by default) possibility that editor that has no access to language Y (from epi setup) is not able to edit and manipulate resources for that language.

In your setup I understand that you want feature that editor A has no access to language Y (because probably it's used by other country site), but still has access to that language via localization provider admin ui? Am I right?

**Comment by euhm** [comment]
Hey,

So in your setup editor A will have access to language X, but not to language Y?
 -> indeed, no delete / change access. The can only read the other translations.

How you differentiate countries? do you distinguish those only by language (culture) in epi?
 -> indeed, each specific culture represents a country

In your setup I understand that you want feature that editor A has no access to language Y (because probably it's used by other country site), but still has access to that language via localization provider admin ui? Am I right?
 -> Ideally yes, if content editor A can't access a specific language, he can't also change that language in the localization provider admin.
But the problem / bug is that if I remove the change access -so when I remove the everyone change rights- the localization doesn't happen anymore. You don't return the language anymore in AvailableLanguagesQuery, so I never receive the available translation for this culture.

**Comment by valdisiljuconoks** [comment]
> "localization doesn't happen anymore"

can you describe this statement a bit more? does not happen anymore in runtime (when you ask for instance Html.Translate()) or you just don't see any more that language in the admin ui?

in general, I think that if current user does not have access to specific language (due to epi access restrictions) - why should editor see that language in available language list & in admin ui resource list?
