### ISSUE TITLE
Mock the DbLocalizationProvider functionality in a UnitTest

### ISSUE THREAD

**Issue by ValtechGuidoTerlouw** [valdisiljuconoks/localization-provider-epi#50]
Hi Valdis,

We are using the DbLocaliztionProvider in our project and I'm trying to unit test some logic that also uses the DbLocaliztionProvider logic, but I'm having trouble with mocking the response of the extension method from the namespace DbLocalizationProvider.

public static class LocalizationServiceExtensions
  {
public static string GetString(
      this LocalizationService service,
      Expression<Func<object>> resource,
      params object[] formatArguments)
    {
      return service.GetStringByCulture(resource, CultureInfo.CurrentUICulture, formatArguments);
    }
...
}

_localizationService.GetString(() => Resources.CreateOrder.Success);

Do you have any tips on how to approach this?
Or maybe an example?

**Comment by valdisiljuconoks** [comment]
Hi,

There are few things that currently (v5.x) is pretty bad designed when it comes to unit testing (statics). This is planned to redesign within next major version timeframe.

However, regarding your question - don't have concrete unit test sample at hand, but can give you couple hints:
* you will need to set instance of localization provider (`LocalizationProvider.Current`)
* that guy under the hood will execute of the queries to get translation (`GetTranslation.Query`)
* handler for that query is registered via `ConfigurationContext.Current.` You can set one with following code:

```
ConfigurationContext.Current.TypeFactory.ForQuery<GetTranslation.Query>().SetHandler<UnitTestTranslationsHandler>();
```

I see that sometimes running unit tests in parallel -> some of them might fail because of shared static state.

If you encounter any issues or challenges - feel free to add those here.

**Comment by ValtechGuidoTerlouw** [comment]
> Hi,
> 
> There are few things that currently (v5.x) is pretty bad designed when it comes to unit testing (statics). This is planned to redesign within next major version timeframe.
> 
> However, regarding your question - don't have concrete unit test sample at hand, but can give you couple hints:
> 
> * you will need to set instance of localization provider (`LocalizationProvider.Current`)
> * that guy under the hood will execute of the queries to get translation (`GetTranslation.Query`)
> * handler for that query is registered via `ConfigurationContext.Current.` You can set one with following code:
> 
> ```
> ConfigurationContext.Current.TypeFactory.ForQuery<GetTranslation.Query>().SetHandler<UnitTestTranslationsHandler>();
> ```
> 
> I see that sometimes running unit tests in parallel -> some of them might fail because of shared static state.
> 
> If you encounter any issues or challenges - feel free to add those here.

I will look into this, thanks for the answer

**Comment by ValtechGuidoTerlouw** [comment]
Hi Valdis,

My unit tests are running smoothly now using your QueryHandler example. Thanks for the help!
